import test from 'node:test';
import assert from 'node:assert/strict';
import {createApi,passwordHash} from '../server/api.mjs';
import {validateLead,qualifies,phoneNumber} from '../server/validation.mjs';
const good={role:'employed',experience:'etf',income:'3500to5000',name:'Testperson',email:'test@example.com',country:'DE',phone:'015123456789',consent:true};
function setup(){const values=new Map();const store={get:async k=>structuredClone(values.get(k)||null),set:async(k,v)=>values.set(k,structuredClone(v)),delete:async k=>values.delete(k),list:async p=>[...values].filter(([k])=>k.startsWith(p)).map(([,v])=>structuredClone(v))};const handler=createApi({store,config:{secret:'test-secret-at-least-32-characters-long',adminEmail:'admin@example.com',passwordHash:passwordHash('a strong test password')}});const request=(path,{method='GET',body,cookie='',origin='https://example.com',ip='test-ip'}={})=>handler(new Request('https://example.com/api/'+path,{method,headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie},...(body?{body:JSON.stringify(body)}:{})}),{ip});return{values,request};}
const cookie=r=>r.headers.get('set-cookie')?.split(';')[0];
test('qualification boundaries, privacy answer, and country phone formats',()=>{
 assert.equal(qualifies('employed','under2500'),false);assert.equal(qualifies('employed','2500to3500'),false);assert.equal(qualifies('employed','3500to5000'),true);assert.equal(qualifies('employed','undisclosed'),true);assert.equal(qualifies('unemployed','over5000'),false);
 assert.equal(phoneNumber('015123456789','DE'),'+4915123456789');assert.equal(phoneNumber('+4915123456789','DE'),'+4915123456789');assert.equal(phoneNumber('004915123456789','DE'),'+4915123456789');assert.equal(phoneNumber('+436641234567','AT'),'+436641234567');assert.equal(phoneNumber('+436641234567','DE'),null);assert.equal(phoneNumber('0151abc23456789','DE'),null);assert.equal(phoneNumber('123','DE'),null);
 assert.ok(validateLead({...good,consent:false}).error);assert.ok(validateLead({...good,email:'broken'}).error);assert.ok(validateLead({...good,income:'forged'}).error);
});
test('server rejects ineligible submissions and does not create leads',async()=>{const{request,values}=setup();const v=await request('experiment');for(const patch of [{income:'under2500'},{income:'2500to3500'},{role:'unemployed'},{phone:'hello'},{consent:false}]){const r=await request('leads',{method:'POST',body:{...good,...patch},cookie:cookie(v)});assert.equal(r.status,422);}assert.equal([...values.keys()].filter(k=>k.startsWith('leads/')).length,0);});
test('qualified submission persists, retries once, and gates booking',async()=>{const{request,values}=setup();assert.equal((await request('booking')).status,403);const v=await request('experiment');const r=await request('leads',{method:'POST',body:good,cookie:cookie(v)});assert.equal(r.status,201);assert.equal((await(await request('booking',{cookie:cookie(r)})).json()).email,good.email);assert.equal((await request('leads',{method:'POST',body:good,cookie:cookie(v)})).status,200);assert.equal([...values.keys()].filter(k=>k.startsWith('leads/')).length,1);assert.equal((await request('booking',{cookie:cookie(r)+'tampered'})).status,403);});
test('admin requires credentials and blocks cross-origin mutations',async()=>{const{request}=setup();assert.equal((await request('admin/leads')).status,401);assert.equal((await request('admin/active',{method:'POST',body:{id:null}})).status,401);assert.equal((await request('login',{method:'POST',body:{email:'admin@example.com',password:'bad'}})).status,401);assert.equal((await request('login',{method:'POST',body:{},origin:'https://evil.test'})).status,403);const login=await request('login',{method:'POST',body:{email:'admin@example.com',password:'a strong test password'}});assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly/);assert.match(login.headers.get('set-cookie'),/Secure/);assert.equal((await request('admin/leads',{cookie:cookie(login)})).status,200);await request('admin/logout',{method:'POST',body:{},cookie:cookie(login)});assert.equal((await request('admin/leads',{cookie:cookie(login)})).status,401);});
test('experiment assignments are stable and attributed even when test is paused before submit',async()=>{const{request}=setup();const login=await request('login',{method:'POST',body:{email:'admin@example.com',password:'a strong test password'}});const admin=cookie(login);const create=await request('admin/experiments',{method:'POST',cookie:admin,body:{name:'CTA test',headline:'',cta:'Strategie erhalten'}});const{id}=await create.json();await request('admin/active',{method:'POST',cookie:admin,body:{id}});const v=await request('experiment'),assignment=await v.json();assert.equal(assignment.id,id);const again=await(await request('experiment',{cookie:cookie(v)})).json();assert.equal(again.variant,assignment.variant);await request('admin/active',{method:'POST',cookie:admin,body:{id:null}});await request('leads',{method:'POST',body:good,cookie:cookie(v)});const results=(await(await request('admin/experiments',{cookie:admin})).json()).experiments[0].results;assert.equal(results.reduce((s,r)=>s+r.visits,0),1);assert.equal(results.find(r=>r.variant===assignment.variant).leads,1);});
test('lead status and notes are persisted, unknown fields are rejected',async()=>{const{request}=setup();const v=await request('experiment');await request('leads',{method:'POST',body:good,cookie:cookie(v)});const login=await request('login',{method:'POST',body:{email:'admin@example.com',password:'a strong test password'}});const admin=cookie(login);const l=(await(await request('admin/leads',{cookie:admin})).json()).leads[0];assert.equal((await request('admin/leads/'+l.id,{method:'PATCH',cookie:admin,body:{status:'appointment',notes:'Rückruf am Montag'}})).status,200);assert.equal((await(await request('admin/leads',{cookie:admin})).json()).leads[0].notes,'Rückruf am Montag');assert.equal((await request('admin/leads/'+l.id,{method:'PATCH',cookie:admin,body:{status:'bad',notes:''}})).status,400);});
test('storage failures do not return false success',async()=>{const api=createApi({store:{get:async()=>{throw Error('offline')}},config:{secret:'test-secret-at-least-32-characters-long'}});assert.equal((await api(new Request('https://example.com/api/experiment'))).status,500);});
test('variant previews are authenticated, show B copy, and do not count visits',async()=>{const{request,values}=setup();const login=await request('login',{method:'POST',body:{email:'admin@example.com',password:'a strong test password'}});const admin=cookie(login);const{id}=await(await request('admin/experiments',{method:'POST',cookie:admin,body:{name:'Preview test',headline:'Alternative Headline',cta:''}})).json();assert.equal((await request('experiment?preview='+id+'&variant=B')).status,401);const preview=await(await request('experiment?preview='+id+'&variant=B',{cookie:admin})).json();assert.equal(preview.headline,'Alternative Headline');assert.equal(preview.preview,true);assert.equal([...values.keys()].filter(k=>k.startsWith('visits/')).length,0);});
