(() => {
 const $=s=>document.querySelector(s);let leads=[],experiments=[],selectedLead=null;
 const statusNames={incomplete:'Kontaktdaten erfasst',disqualified:'Nicht passend',new:'Qualifiziert',contacted:'Kontaktiert',appointment:'Termin vereinbart',won:'Gewonnen',lost:'Verloren',archived:'Archiviert'};
 const roleNames={employed:'Angestellt','self-employed':'Selbstständig',unemployed:'Arbeitslos',other:'Sonstiges'};
 const incomeNames={under2500:'Unter 2.500 €', '2500to3500':'2.500 bis unter 3.500 €','3500to5000':'3.500 bis unter 5.000 €',over5000:'5.000 € oder mehr',undisclosed:'Nicht angegeben'};
 const experienceNames={property:'Besitzt Immobilien',interested:'Interessiert an erster Immobilie',etf:'ETFs / Wertpapiere',none:'Noch keine Investments'};
 const date=value=>new Date(value).toLocaleString('de-DE',{dateStyle:'medium',timeStyle:'short'});
 function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
 async function api(path,options={}){const response=await fetch('/api/'+path,{...options,headers:{'Content-Type':'application/json'},...(options.body?{body:JSON.stringify(options.body)}:{})});let data;try{data=await response.json();}catch{throw Error('Server nicht erreichbar. Bitte aktualisiere die Seite.');}if(response.status===401){$('#dashboard').hidden=true;$('#login-view').hidden=false;document.querySelectorAll('dialog[open]').forEach(d=>d.close());}if(!response.ok)throw Error(data.error||'Die Anfrage ist fehlgeschlagen.');return data;}
 const message=(text)=>{$('#app-message').textContent=text;};
 async function enter(){const me=await api('admin/me');$('#login-view').hidden=true;$('#dashboard').hidden=false;$('#account-label').textContent=me.email;$('#environment').textContent=me.local?'Lokale Entwicklung':'Live · CRM';await refresh();}
 $('#login-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;$('#login-error').textContent='';try{const data=Object.fromEntries(new FormData(event.target));await api('login',{method:'POST',body:data});event.target.password.value='';await enter();}catch(e){$('#login-error').textContent=e.message;}finally{button.disabled=false;}});
 $('#logout').addEventListener('click',async()=>{try{await api('admin/logout',{method:'POST',body:{}});location.reload();}catch(e){message(e.message);}});
 async function refresh(){try{leads=(await api('admin/leads')).leads;renderLeads();await webhookState();}catch(e){message(e.message);}}
 async function webhookState(){const s=await api('admin/webhooks');$('#webhook-state').textContent=(s.configured?'Zapier aktiviert':'Zapier-Versand pausiert / noch nicht konfiguriert')+' · '+s.delivered+' gesendet · '+s.pending+' ausstehend';}
 $('#retry-webhooks').addEventListener('click',async()=>{const b=$('#retry-webhooks');b.disabled=true;try{await api('admin/webhooks/retry',{method:'POST',body:{}});await webhookState();}catch(e){message(e.message);}finally{b.disabled=false;}});
 function filtered(){const query=$('#search').value.toLowerCase(),status=$('#status-filter').value;return leads.filter(l=>(!status||l.status===status)&&`${l.name} ${l.email} ${l.phone}`.toLowerCase().includes(query));}
 function renderLeads(){
  const stats=$('#lead-stats');stats.replaceChildren();for(const [name,count]of [['Anfragen gesamt',leads.filter(l=>l.status!=='archived').length],['Quiz noch offen',leads.filter(l=>l.status==='incomplete').length],['Termin vereinbart',leads.filter(l=>l.status==='appointment').length],['Gewonnen',leads.filter(l=>l.status==='won').length]]){const card=el('div',undefined,'stat');card.append(el('span',name),el('strong',String(count)));stats.append(card);}
  const body=$('#leads-body');body.replaceChildren();const result=filtered();$('#empty-leads').hidden=!!result.length;
  result.forEach(lead=>{const row=el('tr'),contact=el('td');contact.append(el('strong',lead.name),el('small',lead.email),el('small',lead.phone));const profile=el('td');profile.append(el('span',(roleNames[lead.role]||'Noch offen')),el('small',(incomeNames[lead.income]||'Noch offen')));const status=el('td');status.append(el('span',statusNames[lead.status],'status status-'+lead.status));const source=el('td');source.append(el('span',lead.attribution.utm_source||'Direkt'),el('small',lead.experiment==='control'?'Originalseite':`Variante ${lead.variant}`));const action=el('td'),button=el('button','Öffnen →','table-action');button.type='button';button.setAttribute('aria-label',`Lead ${lead.name} öffnen`);button.addEventListener('click',()=>openLead(lead));action.append(button);row.append(contact,profile,status,source,el('td',date(lead.createdAt)),action);body.append(row);});
 }
 function openLead(lead){selectedLead=lead;$('#lead-title').textContent=lead.name;const dl=$('#lead-details');dl.replaceChildren();for(const [name,value]of [['E-Mail',lead.email],['Telefon',lead.phone],['Rolle',(roleNames[lead.role]||'Noch offen')],['Erfahrung',(experienceNames[lead.experience]||'Noch offen')],['Monatsnetto',(incomeNames[lead.income]||'Noch offen')],['Eingang',date(lead.createdAt)],['Kontaktfreigabe',date(lead.consentedAt)],['UTM-Quelle',lead.attribution.utm_source||'–'],['UTM-Medium',lead.attribution.utm_medium||'–'],['Kampagne',lead.attribution.utm_campaign||'–'],['UTM-Content',lead.attribution.utm_content||'–'],['UTM-Term',lead.attribution.utm_term||'–'],['Test',lead.experiment==='control'?'Originalseite':`${lead.experiment} · ${lead.variant}`]])dl.append(el('dt',name),el('dd',value));const form=$('#lead-edit');form.status.value=lead.status;form.notes.value=lead.notes;form.querySelector('.dialog-message').textContent='';$('#lead-dialog').showModal();}
 $('#lead-edit').addEventListener('submit',async event=>{event.preventDefault();event.submitter.disabled=true;try{await api('admin/leads/'+selectedLead.id,{method:'PATCH',body:Object.fromEntries(new FormData(event.target))});$('#lead-dialog').close();await refresh();message('Lead gespeichert.');}catch(e){event.target.querySelector('.dialog-message').textContent=e.message;}finally{event.submitter.disabled=false;}});
 $('#search').addEventListener('input',renderLeads);$('#status-filter').addEventListener('change',renderLeads);$('#refresh').addEventListener('click',refresh);
 $('#export').addEventListener('click',()=>{const cell=v=>'"'+String(v??'').replace(/^(?:[\s]*[=+@\-]|[\t\r\n])/,"'$&").replaceAll('"','""')+'"';const rows=[['Vorname','E-Mail','Telefon','Rolle','Erfahrung','Monatsnetto','Status','Eingang','Quelle','Medium','Kampagne','Content','Term','Weitere UTM-Parameter','Test','Variante','Notiz'],...filtered().map(l=>[l.name,l.email,l.phone,roleNames[l.role],experienceNames[l.experience],incomeNames[l.income],statusNames[l.status],l.createdAt,l.attribution.utm_source,l.attribution.utm_medium,l.attribution.utm_campaign,l.attribution.utm_content,l.attribution.utm_term,JSON.stringify(l.attribution),l.experiment,l.variant,l.notes])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='hamann-leads-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',async()=>{const view=button.dataset.view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b===button));$('#view-leads').hidden=view!=='leads';$('#view-experiments').hidden=view!=='experiments';$('#view-title').textContent=view==='leads'?'Deine Anfragen.':'Deine A/B-Tests.';message('');if(view==='experiments')await loadExperiments();}));
 async function loadExperiments(){try{experiments=(await api('admin/experiments')).experiments;renderExperiments();}catch(e){message(e.message);}}
 function renderExperiments(){const list=$('#experiments-list');list.replaceChildren();if(!experiments.length)list.append(el('p','Noch kein Test angelegt. Die Originalseite ist unverändert aktiv.','empty'));for(const exp of experiments){const panel=el('article',undefined,'panel experiment');const header=el('div',undefined,'panel-toolbar');const info=el('div');info.append(el('span',exp.active?'LÄUFT · 50 / 50':'INAKTIV','eyebrow'),el('h2',exp.name));const toggle=el('button',exp.active?'Test pausieren':'Test aktivieren',exp.active?'secondary':'primary');toggle.addEventListener('click',async()=>{toggle.disabled=true;try{await api('admin/active',{method:'POST',body:{id:exp.active?null:exp.id}});await loadExperiments();message(exp.active?'Test pausiert. Neue Seitenaufrufe zeigen das Original.':'Test aktiviert. Alle anderen Tests sind pausiert.');}catch(e){message(e.message);toggle.disabled=false;}});header.append(info,toggle);panel.append(header);const variants=el('div',undefined,'variant-grid');for(const result of exp.results){const card=el('div',undefined,'variant-card');card.append(el('h3','Variante '+result.variant),el('p',result.variant==='A'?'Bestehende Headline und Buttons':(exp.headline||'Bestehende Headline')),el('small',result.variant==='B'&&exp.cta?'Button: '+exp.cta:'Bestehende Buttontexte'));const metrics=el('div',undefined,'variant-metrics');metrics.append(el('strong',result.visits+' Besuche'),el('strong',result.leads+' Anfragen'),el('strong',result.visits?((result.leads/result.visits)*100).toFixed(1)+' %':'–'));const preview=el('a','Vorschau öffnen ↗','preview-link');preview.href='../?'+new URLSearchParams({preview:exp.id,variant:result.variant});preview.target='_blank';preview.rel='noopener';card.append(metrics,preview);variants.append(card);}panel.append(variants,el('p','Deskriptive Ergebnisse. Bei wenigen Besuchen lässt sich daraus noch kein verlässlicher Gewinner ableiten.','metric-note'));list.append(panel);}}
 $('#new-test').addEventListener('click',()=>{$('#test-form').reset();$('#test-form .dialog-message').textContent='';$('#test-dialog').showModal();});
 $('#test-form').addEventListener('submit',async event=>{event.preventDefault();event.submitter.disabled=true;try{await api('admin/experiments',{method:'POST',body:Object.fromEntries(new FormData(event.target))});$('#test-dialog').close();await loadExperiments();message('Entwurf gespeichert. Die Live-Seite ändert sich erst mit „Test aktivieren“.');}catch(e){event.target.querySelector('.dialog-message').textContent=e.message;}finally{event.submitter.disabled=false;}});
 document.querySelectorAll('dialog .close').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
 enter().catch(()=>{});
})();
